[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn \"app:create_app()\" --bind 0.0.0.0:$PORT --workers 2"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
